version: '3'
volumes:
  postgres-data:
  
services:
  backend-golang:
    build: 
      context: ./be-src
      dockerfile: Dockerfile
    env_file:
        - ./.env.${BE_ENV}
    volumes:
      - .:/workspace:cached
    command: sleep infinity
    network_mode: service:db-postgres
    
  db-postgres:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env.${DB_ENV}
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  frontend-nextjs:
    build: 
      context: ./fe-src
      target: ${FE_ENV}
      dockerfile: Dockerfile
    volumes:
      - .:/workspace:cached
      - /node_modules
    env_file:
      - ./.env.${FE_ENV}
    ports:
      - "3000:3000"