import type { IconType } from "./icons-local";
import {
  SiAlibabacloud,
  SiAndroid,
  SiApacheairflow,
  SiApachespark,
  SiApple,
  SiAuth0,
  SiCloudera,
  SiDocker,
  SiGin,
  SiGithubactions,
  SiGo,
  SiGooglegemini,
  SiGooglebigquery,
  SiKubernetes,
  SiLooker,
  SiMysql,
  SiOpenapiinitiative,
  SiOpenjdk,
  SiPostgresql,
  SiPython,
  SiReact,
  SiRedis,
  SiSap,
  SiTypescript,
  SiXcode,
} from "./icons-local";
import {
  TbChartBar,
  TbCode,
  TbDatabase,
  TbFileSpreadsheet,
  TbFolderShare,
  TbTestPipe,
  TbTransform,
} from "./icons-local";

const MAP: Record<string, IconType> = {
  "AliCloud OSS": SiAlibabacloud,
  "Alibaba Cloud": SiAlibabacloud,
  "MaxCompute": SiAlibabacloud,
  "Android": SiAndroid,
  "UiAutomator": SiAndroid,
  "Apache Airflow": SiApacheairflow,
  "Apache Spark": SiApachespark,
  "BigQuery": SiGooglebigquery,
  "CI/CD": SiGithubactions,
  "DBT": TbTransform,
  "ERP": SiSap,
  "Espresso": TbTestPipe,
  "Excel": TbFileSpreadsheet,
  "VBA": TbFileSpreadsheet,
  "Gin": SiGin,
  "Go": SiGo,
  "Docker": SiDocker,
  "PostgreSQL": SiPostgresql,
  "GCP": SiAlibabacloud,
  "Python": SiPython,
  "Google Data Studio": SiLooker,
  "Looker Studio": SiLooker,
  "Hive": SiApachespark,
  "Impala": SiCloudera,
  "Java": SiOpenjdk,
  "Kubernetes": SiKubernetes,
  "MySQL": SiMysql,
  "OAuth": SiAuth0,
  "Objective-C": SiApple,
  "iOS": SiApple,
  "REST API": SiOpenapiinitiative,
  "React": SiReact,
  "Redis": SiRedis,
  "SFTP": TbFolderShare,
  "SQL": TbDatabase,
  "Tableau": TbChartBar,
  "TypeScript": SiTypescript,
  "Vertex AI": SiGooglegemini,
  "XCUITest": SiXcode,
};

export function techIcon(name: string): IconType {
  return MAP[name] ?? TbCode;
}
